stages:
  - build
  
docker-build-master:
  # Official docker image.
  image: docker/compose:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker-compose version
    - docker-compose up -d

