# Generated by Django 3.0.5 on 2021-05-24 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialvoiceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
