# Generated by Django 3.0.5 on 2021-04-18 00:41

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('socialvoiceapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, storage=djongo.storage.GridFSStorage(base_url='./myfiles/', collection='myfiles'), upload_to='avatars'),
        ),
    ]
