# Generated by Django 3.0.5 on 2021-05-24 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialvoiceapp', '0004_auto_20210524_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 18, 35, 25, 416510)),
        ),
        migrations.AlterField(
            model_name='city',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
