# Generated by Django 3.0.5 on 2021-04-18 00:43

from django.db import migrations, models
import djongo.storage
import socialvoiceapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('socialvoiceapp', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, storage=djongo.storage.GridFSStorage(base_url='./myfiles/', collection='myfiles'), upload_to='avatars', validators=[socialvoiceapp.validators.validate_image_file_extension]),
        ),
    ]
