# Generated by Django 3.0.5 on 2021-05-24 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialvoiceapp', '0005_auto_20210524_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
