# Generated by Django 3.0.5 on 2021-05-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialvoiceapp', '0006_auto_20210524_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiomessage',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='_id',
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
