# Generated by Django 3.0.5 on 2021-04-18 14:01

from django.db import migrations, models
import django.db.models.deletion
import djongo.storage
import socialvoiceapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('socialvoiceapp', '0006_auto_20210418_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_data', models.FileField(null=True, storage=djongo.storage.GridFSStorage(base_url='myfiles/', collection='myfiles'), upload_to='messages', validators=[socialvoiceapp.validators.validate_audio_file_extension])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialvoiceapp.Profile')),
            ],
        ),
    ]
